#!/usr/bin/env python3
"""
Module 08: ERGM Analysis Preparation for Lorraine Witchcraft Trials
Prepares network data for Exponential Random Graph Models (ERGM) in R.

ERGM allows testing hypotheses about network formation:
- Do witnesses tend to testify against people they're connected to?
- Is there gender homophily in the accusation network?
- Do structural holes (brokerage positions) predict tie formation?

Requirements:
- R with ergm package (install.packages("ergm") in R)
- rpy2 for Python-R integration (optional)
"""

import json
from pathlib import Path
from typing import Dict, List
import pandas as pd
import numpy as np
import networkx as nx
import warnings
warnings.filterwarnings('ignore')

# Configuration
BASE_DIR = Path("/Users/natebaker/Desktop/analysis/2025/sna_pipeline")
NETWORK_DIR = BASE_DIR / "output/networks"
ENTITY_DIR = BASE_DIR / "output/entities"
OUTPUT_DIR = BASE_DIR / "output/models/ergm"
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)


class ERGMDataPreparation:
    """
    Prepare network data for ERGM analysis in R.
    """

    def __init__(self):
        self.G = None
        self.testimony_G = None  # Testimony-only subgraph

    def load_data(self):
        """Load network data."""
        print("Loading data...")

        self.G = nx.read_graphml(NETWORK_DIR / "full_network.graphml")
        print(f"  Full network: {self.G.number_of_nodes()} nodes, {self.G.number_of_edges()} edges")

        # Create testimony-only subgraph for ERGM
        testimony_edges = [(u, v, d) for u, v, d in self.G.edges(data=True)
                          if d.get('relationship_type') == 'TESTIFIED_AGAINST']
        self.testimony_G = nx.DiGraph()
        self.testimony_G.add_edges_from(testimony_edges)

        # Copy node attributes
        for node in self.testimony_G.nodes():
            if node in self.G.nodes:
                self.testimony_G.nodes[node].update(self.G.nodes[node])

        print(f"  Testimony network: {self.testimony_G.number_of_nodes()} nodes, "
              f"{self.testimony_G.number_of_edges()} edges")

    def prepare_node_attributes(self) -> pd.DataFrame:
        """Prepare node attribute dataframe for R."""
        print("\n=== Preparing Node Attributes ===")

        # Identify witnesses and accused from edge directions
        accused_set = set(v for u, v in self.testimony_G.edges())
        witness_set = set(u for u, v in self.testimony_G.edges())

        records = []
        for node in self.testimony_G.nodes():
            attrs = self.testimony_G.nodes[node]

            gender = attrs.get('gender', 'unknown')

            records.append({
                'node_id': node,
                'is_accused': int(node in accused_set),
                'is_witness': int(node in witness_set),
                'gender_female': int(gender == 'female'),
                'gender_male': int(gender == 'male'),
                'gender_unknown': int(gender not in ['male', 'female']),
                'in_degree': self.testimony_G.in_degree(node),
                'out_degree': self.testimony_G.out_degree(node),
            })

        df = pd.DataFrame(records)
        print(f"  Node attributes: {len(df)} nodes")
        print(f"  Gender: {df['gender_female'].sum()} female, {df['gender_male'].sum()} male")

        return df

    def export_edgelist(self) -> pd.DataFrame:
        """Export edge list for R."""
        print("\n=== Exporting Edge List ===")

        edges = []
        for u, v, data in self.testimony_G.edges(data=True):
            edges.append({
                'source': u,
                'target': v,
                'relationship': data.get('relationship_type', 'unknown'),
            })

        df = pd.DataFrame(edges)
        print(f"  Edges: {len(df)}")

        return df

    def create_adjacency_matrix(self) -> np.ndarray:
        """Create adjacency matrix for ERGM."""
        print("\n=== Creating Adjacency Matrix ===")

        nodes = list(self.testimony_G.nodes())
        n = len(nodes)
        node_idx = {node: i for i, node in enumerate(nodes)}

        adj_matrix = np.zeros((n, n), dtype=int)

        for u, v in self.testimony_G.edges():
            if u in node_idx and v in node_idx:
                adj_matrix[node_idx[u], node_idx[v]] = 1

        print(f"  Adjacency matrix: {n}x{n}")
        print(f"  Density: {adj_matrix.sum() / (n * (n-1)):.6f}")

        return adj_matrix, nodes

    def generate_r_script(self) -> str:
        """Generate R script for ERGM analysis."""
        print("\n=== Generating R Script ===")

        r_script = '''# ERGM Analysis for Lorraine Witchcraft Trials
# Generated by Module 08
#
# This script fits Exponential Random Graph Models to the testimony network
# to test hypotheses about network formation processes.

# Install required packages if needed
# install.packages(c("ergm", "network", "statnet"))

library(ergm)
library(network)

# Set working directory to ERGM output folder
setwd("output/models/ergm")

# ============================================================
# Load Data
# ============================================================

# Load edge list
edges <- read.csv("testimony_edges.csv", stringsAsFactors = FALSE)

# Load node attributes
nodes <- read.csv("node_attributes.csv", stringsAsFactors = FALSE)

# Create network object
n_nodes <- nrow(nodes)
net <- network(edges[, c("source", "target")],
               directed = TRUE,
               vertices = nodes$node_id)

# Add node attributes
set.vertex.attribute(net, "is_accused", nodes$is_accused)
set.vertex.attribute(net, "is_witness", nodes$is_witness)
set.vertex.attribute(net, "gender_female", nodes$gender_female)
set.vertex.attribute(net, "gender_male", nodes$gender_male)

cat("Network loaded:", network.size(net), "nodes,", network.edgecount(net), "edges\\n")

# ============================================================
# Model 1: Baseline (Edges only)
# ============================================================

cat("\\n=== Model 1: Baseline ===\\n")
model1 <- ergm(net ~ edges)
summary(model1)

# ============================================================
# Model 2: Add Reciprocity
# ============================================================

cat("\\n=== Model 2: + Reciprocity ===\\n")
model2 <- ergm(net ~ edges + mutual,
               control = control.ergm(MCMC.samplesize = 10000))
summary(model2)

# ============================================================
# Model 3: Add Gender Effects
# ============================================================

cat("\\n=== Model 3: + Gender Homophily ===\\n")
model3 <- ergm(net ~ edges + mutual +
               nodematch("gender_female") +
               nodeifactor("gender_female") +
               nodeofactor("gender_female"),
               control = control.ergm(MCMC.samplesize = 10000))
summary(model3)

# ============================================================
# Model 4: Add Structural Effects
# ============================================================

cat("\\n=== Model 4: + Structural Effects ===\\n")
model4 <- ergm(net ~ edges + mutual +
               nodematch("gender_female") +
               nodeifactor("gender_female") +
               nodeofactor("gender_female") +
               gwesp(0.5, fixed = TRUE) +  # Triadic closure
               gwdsp(0.5, fixed = TRUE),   # Two-paths
               control = control.ergm(MCMC.samplesize = 20000,
                                     MCMLE.maxit = 100))
summary(model4)

# ============================================================
# Model Comparison
# ============================================================

cat("\\n=== Model Comparison (AIC) ===\\n")
cat("Model 1 (Edges):", AIC(model1), "\\n")
cat("Model 2 (+ Reciprocity):", AIC(model2), "\\n")
cat("Model 3 (+ Gender):", AIC(model3), "\\n")
cat("Model 4 (+ Structure):", AIC(model4), "\\n")

# ============================================================
# Goodness of Fit
# ============================================================

cat("\\n=== Goodness of Fit for Best Model ===\\n")
gof4 <- gof(model4)
print(gof4)

# Save GOF plot
pdf("ergm_gof.pdf", width = 10, height = 8)
plot(gof4)
dev.off()
cat("GOF plot saved to ergm_gof.pdf\\n")

# ============================================================
# Save Results
# ============================================================

# Save model summaries
sink("ergm_results.txt")
cat("ERGM Analysis Results - Lorraine Witchcraft Trials\\n")
cat("=" , rep("=", 60), "\\n\\n", sep = "")

cat("\\n--- Model 1: Baseline ---\\n")
print(summary(model1))

cat("\\n--- Model 2: + Reciprocity ---\\n")
print(summary(model2))

cat("\\n--- Model 3: + Gender Homophily ---\\n")
print(summary(model3))

cat("\\n--- Model 4: + Structural Effects ---\\n")
print(summary(model4))

cat("\\n--- AIC Comparison ---\\n")
cat("Model 1:", AIC(model1), "\\n")
cat("Model 2:", AIC(model2), "\\n")
cat("Model 3:", AIC(model3), "\\n")
cat("Model 4:", AIC(model4), "\\n")
sink()

cat("\\nResults saved to ergm_results.txt\\n")

# ============================================================
# Coefficient Interpretation
# ============================================================

cat("\\n=== Key Findings ===\\n")
coef4 <- coef(model4)
se4 <- sqrt(diag(vcov(model4)))
z4 <- coef4 / se4

for (i in 1:length(coef4)) {
  sig <- ""
  if (abs(z4[i]) > 2.58) sig <- "***"
  else if (abs(z4[i]) > 1.96) sig <- "**"
  else if (abs(z4[i]) > 1.65) sig <- "*"

  cat(sprintf("%-30s: %7.3f (SE=%5.3f, z=%5.2f) %s\\n",
              names(coef4)[i], coef4[i], se4[i], z4[i], sig))
}

cat("\\n* p<0.10, ** p<0.05, *** p<0.01\\n")
'''
        return r_script

    def save_outputs(self, node_attrs: pd.DataFrame, edges: pd.DataFrame,
                    adj_matrix: np.ndarray, nodes: List[str], r_script: str):
        """Save all ERGM preparation outputs."""
        print("\n=== Saving Outputs ===")

        # Save node attributes
        node_attrs.to_csv(OUTPUT_DIR / "node_attributes.csv", index=False)
        print(f"  Saved node_attributes.csv")

        # Save edge list
        edges.to_csv(OUTPUT_DIR / "testimony_edges.csv", index=False)
        print(f"  Saved testimony_edges.csv")

        # Save adjacency matrix
        np.savetxt(OUTPUT_DIR / "adjacency_matrix.csv", adj_matrix, delimiter=",", fmt="%d")
        print(f"  Saved adjacency_matrix.csv")

        # Save node order
        with open(OUTPUT_DIR / "node_order.json", 'w') as f:
            json.dump(nodes, f)
        print(f"  Saved node_order.json")

        # Save R script
        with open(OUTPUT_DIR / "run_ergm.R", 'w') as f:
            f.write(r_script)
        print(f"  Saved run_ergm.R")

        # Save README
        readme = """# ERGM Analysis for Lorraine Witchcraft Trials

## Files
- `node_attributes.csv`: Node-level attributes (gender, accused/witness status)
- `testimony_edges.csv`: Edge list of TESTIFIED_AGAINST relationships
- `adjacency_matrix.csv`: Binary adjacency matrix
- `node_order.json`: Node names corresponding to matrix rows/columns
- `run_ergm.R`: R script for ERGM analysis

## Running the Analysis

### Prerequisites
1. Install R (https://cran.r-project.org/)
2. Install required R packages:
   ```R
   install.packages(c("ergm", "network", "statnet"))
   ```

### Execution
1. Open R or RStudio
2. Set working directory to the sna_pipeline folder
3. Run the script:
   ```R
   source("output/models/ergm/run_ergm.R")
   ```

### Interpretation
The ERGM models test the following hypotheses:

1. **Reciprocity**: Do witnesses testify against people who testified against them?
   - Positive `mutual` coefficient = reciprocal accusation patterns

2. **Gender Homophily**: Do same-gender individuals accuse each other more often?
   - Positive `nodematch.gender_female` = women accuse women more

3. **Gender Sender Effects**: Are certain genders more likely to testify?
   - `nodeofactor.gender_female` = women's propensity to be witnesses

4. **Gender Receiver Effects**: Are certain genders more likely to be accused?
   - `nodeifactor.gender_female` = women's propensity to be accused

5. **Triadic Closure (GWESP)**: Do accusation chains form triangles?
   - Positive GWESP = if A accuses B and B accuses C, A more likely to accuse C

6. **Two-Paths (GWDSP)**: Do accusations flow through intermediaries?
   - Positive GWDSP = indirect accusation paths are common
"""
        with open(OUTPUT_DIR / "README.md", 'w') as f:
            f.write(readme)
        print(f"  Saved README.md")

        # Save summary stats
        summary = {
            'n_nodes': len(nodes),
            'n_edges': len(edges),
            'n_accused': int(node_attrs['is_accused'].sum()),
            'n_witnesses': int(node_attrs['is_witness'].sum()),
            'n_female': int(node_attrs['gender_female'].sum()),
            'n_male': int(node_attrs['gender_male'].sum()),
            'density': float(adj_matrix.sum() / (len(nodes) * (len(nodes) - 1))),
        }
        with open(OUTPUT_DIR / "ergm_data_summary.json", 'w') as f:
            json.dump(summary, f, indent=2)
        print(f"  Saved ergm_data_summary.json")

    def run(self):
        """Execute the full ERGM data preparation pipeline."""
        print("=" * 70)
        print("ERGM DATA PREPARATION PIPELINE")
        print("=" * 70)

        # Load data
        self.load_data()

        # Prepare outputs
        node_attrs = self.prepare_node_attributes()
        edges = self.export_edgelist()
        adj_matrix, nodes = self.create_adjacency_matrix()
        r_script = self.generate_r_script()

        # Save outputs
        self.save_outputs(node_attrs, edges, adj_matrix, nodes, r_script)

        print("\n" + "=" * 70)
        print("PREPARATION COMPLETE")
        print("=" * 70)
        print(f"\nOutputs saved to: {OUTPUT_DIR}")
        print("\nTo run ERGM analysis:")
        print("  1. Install R and the 'ergm' package")
        print("  2. Run: Rscript output/models/ergm/run_ergm.R")

        return node_attrs, edges


if __name__ == "__main__":
    prep = ERGMDataPreparation()
    prep.run()
