# ERGM Analysis for Lorraine Witchcraft Trials
# Generated by Module 08
#
# This script fits Exponential Random Graph Models to the testimony network
# to test hypotheses about network formation processes.

# Install required packages if needed
# install.packages(c("ergm", "network", "statnet"))

library(ergm)
library(network)

# Set working directory to ERGM output folder
setwd("output/models/ergm")

# ============================================================
# Load Data
# ============================================================

# Load edge list
edges <- read.csv("testimony_edges.csv", stringsAsFactors = FALSE)

# Load node attributes
nodes <- read.csv("node_attributes.csv", stringsAsFactors = FALSE)

# Create network object
n_nodes <- nrow(nodes)
net <- network(edges[, c("source", "target")],
               directed = TRUE,
               vertices = nodes$node_id)

# Add node attributes
set.vertex.attribute(net, "is_accused", nodes$is_accused)
set.vertex.attribute(net, "is_witness", nodes$is_witness)
set.vertex.attribute(net, "gender_female", nodes$gender_female)
set.vertex.attribute(net, "gender_male", nodes$gender_male)

cat("Network loaded:", network.size(net), "nodes,", network.edgecount(net), "edges\n")

# ============================================================
# Model 1: Baseline (Edges only)
# ============================================================

cat("\n=== Model 1: Baseline ===\n")
model1 <- ergm(net ~ edges)
summary(model1)

# ============================================================
# Model 2: Add Reciprocity
# ============================================================

cat("\n=== Model 2: + Reciprocity ===\n")
model2 <- ergm(net ~ edges + mutual,
               control = control.ergm(MCMC.samplesize = 10000))
summary(model2)

# ============================================================
# Model 3: Add Gender Effects
# ============================================================

cat("\n=== Model 3: + Gender Homophily ===\n")
model3 <- ergm(net ~ edges + mutual +
               nodematch("gender_female") +
               nodeifactor("gender_female") +
               nodeofactor("gender_female"),
               control = control.ergm(MCMC.samplesize = 10000))
summary(model3)

# ============================================================
# Model 4: Add Structural Effects
# ============================================================

cat("\n=== Model 4: + Structural Effects ===\n")
model4 <- ergm(net ~ edges + mutual +
               nodematch("gender_female") +
               nodeifactor("gender_female") +
               nodeofactor("gender_female") +
               gwesp(0.5, fixed = TRUE) +  # Triadic closure
               gwdsp(0.5, fixed = TRUE),   # Two-paths
               control = control.ergm(MCMC.samplesize = 20000,
                                     MCMLE.maxit = 100))
summary(model4)

# ============================================================
# Model Comparison
# ============================================================

cat("\n=== Model Comparison (AIC) ===\n")
cat("Model 1 (Edges):", AIC(model1), "\n")
cat("Model 2 (+ Reciprocity):", AIC(model2), "\n")
cat("Model 3 (+ Gender):", AIC(model3), "\n")
cat("Model 4 (+ Structure):", AIC(model4), "\n")

# ============================================================
# Goodness of Fit
# ============================================================

cat("\n=== Goodness of Fit for Best Model ===\n")
gof4 <- gof(model4)
print(gof4)

# Save GOF plot
pdf("ergm_gof.pdf", width = 10, height = 8)
plot(gof4)
dev.off()
cat("GOF plot saved to ergm_gof.pdf\n")

# ============================================================
# Save Results
# ============================================================

# Save model summaries
sink("ergm_results.txt")
cat("ERGM Analysis Results - Lorraine Witchcraft Trials\n")
cat("=" , rep("=", 60), "\n\n", sep = "")

cat("\n--- Model 1: Baseline ---\n")
print(summary(model1))

cat("\n--- Model 2: + Reciprocity ---\n")
print(summary(model2))

cat("\n--- Model 3: + Gender Homophily ---\n")
print(summary(model3))

cat("\n--- Model 4: + Structural Effects ---\n")
print(summary(model4))

cat("\n--- AIC Comparison ---\n")
cat("Model 1:", AIC(model1), "\n")
cat("Model 2:", AIC(model2), "\n")
cat("Model 3:", AIC(model3), "\n")
cat("Model 4:", AIC(model4), "\n")
sink()

cat("\nResults saved to ergm_results.txt\n")

# ============================================================
# Coefficient Interpretation
# ============================================================

cat("\n=== Key Findings ===\n")
coef4 <- coef(model4)
se4 <- sqrt(diag(vcov(model4)))
z4 <- coef4 / se4

for (i in 1:length(coef4)) {
  sig <- ""
  if (abs(z4[i]) > 2.58) sig <- "***"
  else if (abs(z4[i]) > 1.96) sig <- "**"
  else if (abs(z4[i]) > 1.65) sig <- "*"

  cat(sprintf("%-30s: %7.3f (SE=%5.3f, z=%5.2f) %s\n",
              names(coef4)[i], coef4[i], se4[i], z4[i], sig))
}

cat("\n* p<0.10, ** p<0.05, *** p<0.01\n")
